### PR TITLE
Remove dependency on RPi.GPIO

### PR DESCRIPTION
**Pull request by paul-1**
Cubotino is already using gpiozero/pigpio for the pwm stuff, just use it for all gpio function.  I tested all of the functions of the touch button that I could make out in the code (Solve. Shuffle, Stop)

### CODE REVIEW

**Comment by paul-1** [comment]
Going to have to come back at this, since the SPI display drivers require it.   RPi.GPIO wont work with a pi5 (Not that anyone would want to run a cubotino on a pi5.

**Comment by AndreaFavero71** [comment]
If I remember well, the gpiozero is quite underperforming on the interrupts.
The only momet this is relevant in Cubotino, is when the robot needs to be stopped quickly, i.e. because of jammed parts/cube while setting things up.
It might be that gpiozero is now more efficient, but I haven't further checked.

**Comment by paul-1** [comment]
If you use the pigpio pin factory, for the pin control, the interrupt seemed fine.

Gpio is a mess right now, RPi is transitioning to kernel gpio support.

Both RPi.GPIO and pipgpio are obsolete. Neither work on the Pi5.  Granted the pi5 is not a target for cubotino....

The st7735 v1.0 driver has already been updated to gpiod and the developer of pigpio has transitioned to lgpio both of which use the kernel libgpiod drivers.  Will need to figure this out to transition to newer kernels and Bookworm.

Perhaps I'll just let things settle for a bit and just solve some cubes.

**Comment by AndreaFavero71** [comment]
I don't have such a deep knowledge, I'm glad you have it :-)

**Pull request closed without merging**
